### ISSUE TITLE
Non-rigid registration?

### ISSUE THREAD

**Issue by phiwei** [lNefarin/ANHIR_MW#1]
Thank you very much for making this code publicly available. 

While reading through your method, I was wondering what part of the method include non-rigid transformations. Particularly, the function `partial_data_registration_global()` is located in `nonrigid_registration.py`. 

However, it gets called prior to Step 3 - Nonrigid Registration. When reading the code, I could also not spot any non-rigid transformation in this function. Am I not noticing something about this function, or is it correct that `partial_data_registration_global()` only performs rigid transformation?

Thanks!

**Comment by MWod** [comment]
The nonrigid registration is performed by the MIND-based Demons algorithm `dm` or the local affine transformation (well, assuming that the local affine transformation is a deformable one) `partial_data_registration_local`. Both the functions are in the `nonrigid_registration.py`.

Sorry for the late response.

Bests,
